### PR TITLE
remove setlocale logic

### PR DESCRIPTION
**Pull request by did-g**
Hi,
setlocale usage can corrupt GPS reading.

How to reproduce:
when receiving gps data, open draw dialog box on a linux system with locale using comma as decimal separator (aka continental Europe) , GPS positions are now truncated to degrees minutes.

Anyway every other opencpn dialogs are using '.' for decimal separator even for locale with LC_NUMERIC ','.

Regards
Didier

### CODE REVIEW

**Comment by jongough** [comment]
Hi Didier,
   We had a bit of a discussion about localisation in the thread "PlugIns and internationalisation " (http://www.cruisersforum.com/forums/f134/plugins-and-internationalisation-160929.html) and there is an issue within OCPN that it is not handling it correctly. The consensus was that the american ideal should not be forced on non americans. I would prefer not to remove this code, rather it should be corrected to show the correct use of LC_NUMERIC. For compatibility with XML implementations the '.' (dot) is used for decimals when creating/reading xml input files, but in displays either the '.' (dot) or ',' (comma) should be used depending on the localisation setting.

   I will have a look and see if I can find out what is going on, but my 'normal' language uses the '.' (dot) so it is more difficult for me to test this and find all the wrinkles.

Regards
   Jon

**Comment by did-g** [comment]
Hi,

I agree it'd be nicer but I'm not sure it's possible because NMEA and
a lot of other stuffs are using functions which are locale sensitive,
ie converting text to double and setlocale is a per process attribute.
for example with a comma separator:
$GPRMC,074118,A,5021.5076,N,00407.2382,W,0.0,90.0,030711,4.0,W,A*23
5021.5076 ==> 5021
00407.2382 ==> 00407
and so on.

There's a  per thread version of setlocale but in my understanding
it's not enough, it should switch back to LC_NUMERIC C every time the
program wxyield (ie UI loop) in the same thread.
Moreover setlocale can be slow . (on linux it could open and mmap
files) so doing it before every conversion may not be an option and
it'd be error prone.

IIRC the biggest issue on window is that by default the numeric keypad
dot key is remapped to comma so entering decimal numbers with dot is a
pain but setlocale calls are already disable on window.

Anyway if you need more testing i'm there.

Regards
Didier

**Comment by jongough** [comment]
Hi,
   I understand, but I did get some negative comments about not respecting location and using the wrong separator, so this was my attempt to sort it out. The only time it appears to be an issue is when a dialog box is open and is displaying the current lat/lon. At that time the performance should not be an issue (well not too much of an issue). So I would prefer to correct the display in the dialog boxes and leave the other stuff alone.

   As for performance there is a general issue with OCPN on smaller processors, i.e. PI, that have enough processors, but OCPN only makes real use of one. It would be worth multithreading OCPN so that JSON messages and possibly screen draws run on different threads to the standard processing. At least this way slower cpu's with multiple cores would work better. But that is a discussion for a thread in the forum.

Regards
   Jon

**Comment by jongough** [comment]
Hi,
   I am trying to recreate the issue, but whilst I have picked French for the language the decimal separator is a '.' (dot), not a ',' (comma). That may be because my machine is running english whilst ocpn is running french (I have also tried german). I will try a virtual machine and change it across to french and see what happens.

Jon

**Comment by did-g** [comment]
Hi,

For me:
- using today OD and Dave master on Linux.
- OCPN French setting.

Boat position in degree minutes decimal is using a . (as displayed in
bottom status bar)

- create a boundary zone.

- open OD and boundary zone dialog box

- Replay a VDR file over the network with dialog box open

Positions in degree minutes decimal are using a , in OD dialog box but
boat position is truncated to minutes in status bar even if displayed
with a '.'  (speed is using a , and is truncated too).

Closing/opening boundary zone properties dialog box switch between
full and truncated values.

Hope it helps.

Regards
Didier

**Comment by jongough** [comment]
Hi,
   I found an issue in the setting and resetting of the locale when OD dialog boxes were displayed. I have fixed this in patch 1.4.33. I did manage to setup a runnable linux (under VB which currently has some issues) and set the language in both Linux and OCPN to French and then replayed a VDR file to see the issue. Using this setup there is no truncation of the boat position (it was flicking between the decimal position and zero which indicated it was the update routines for dialogs causing the issue. 

   The switching of locale only occurs when an OD dialog box is open and when the XML and config files are saved. So in most cases this is not occurring too frequently.

Regards
   Jon

**Comment by jongough** [comment]
Hi,
   I found an issue in the setting and resetting of the locale when OD dialog boxes were displayed. I have fixed this in patch 1.4.33. I did manage to setup a runnable linux (under VB which currently has some issues) and set the language in both Linux and OCPN to French and then replayed a VDR file to see the issue. Using this setup there is no truncation of the boat position (it was flicking between the decimal position and zero which indicated it was the update routines for dialogs causing the issue. 

   The switching of locale only occurs when an OD dialog box is open and when the XML and config files are saved. So in most cases this is not occurring too frequently.

Regards
   Jon

**Comment by did-g** [comment]
Great, I will try .

**Comment by rgleason** [comment]
I wonder if this is resolved and should be closed?

**Comment by rgleason** [comment]
Perhaps this should be closed?

**Comment by jongough** [comment]
Has been fixed

**Pull request closed without merging**
