### PR TITLE
Updates 1.6

### PR DESCRIPTION
**Pull request by priyankaprakasan**

### CODE REVIEW

**Comment by priyankaprakasan** [comment]
Dear Jong

May I  know why are you closing this pull request?
Otherwise where I should put this request,  am I placing this pull request
in a wrong way?

**Comment by jongough** [comment]
You are not providing any code and you are messing up my branches. If you want to provide code then create your own branch in your own clone of this repository then push your updates to your github repository, then create a pull request for your changes against this repository.

If you want to report a problem or suggest a change then use the 'Issues' section of this repository.

**Comment by priyankaprakasan** [comment]
My apologies Jong for messing up your code. I really had no idea that how
to place a new request.

And I have already tried to push my code to git hub, but as I told you I
get an error(Please see the attachment).
I am always ready to share my code, please don't misunderstand me. I am
pushing code to git hub for the first time.

**Comment by jongough** [comment]
You need to clone the respository to your local machine, then you need to create a new branch based on master, then make your changes, push the changes to your github.com repository (you will need to setup an account on github to do this) version of my repository, you will then be offered the ability to create a pull request which I can see and can have a look at.

**Comment by priyankaprakasan** [comment]
Dear Jon,

I have created a pull request in my git hub account and hope now you can
see the codes I have modified.



*Regards*

Priyanka

**Pull request closed without merging**
