### PR TITLE
Removed some wxASSERTS.

### PR DESCRIPTION
**Pull request by transmitterdan**
I ran this new version of the PI against the latest git version of wxWidgets. These were the asserts I could trigger.

Dan

### CODE REVIEW

**Comment by jongough** [comment]
This should have been incorporated into patch 1.4.24.

What platform and how are you triggering the asserts, it does not appear to happen for me?

Regards
   Jon

**Comment by transmitterdan** [comment]
I am using Windows with Visual Studio 2017. I link against wxWidgets latest git version.

This combination finds the most future incompatibilities. It also allows to test ahead of a possible switch to the most recent wxWidgets library. 

Beat regards,
Dan

**Comment by jongough** [comment]
When I compile now with wxWidgets 3.0.3 I do not get any errors. Can you try with 1.4.24 and see if you get any?

Thanks

**Comment by transmitterdan** [comment]
I am trying V1.4.26 now. I am hitting a new assert in ODNavObjectChanges.cpp line 259.

```
    if(pop->m_sTypeString == wxT("Boundary Point")) {
        BoundaryPoint *bp = dynamic_cast<BoundaryPoint *>(pop);
        assert(bp != 0);
```
When I open the Path & Point Manager dialog and select OD Points tab. Then if there are no points listed and I click the New button the assert fails. The pop pointer is valid and it has m_sTypeString == "Boundary Point" but the dynamic_cast somehow fails and the resulting pointer bp is NULL.

**Comment by jongough** [comment]
Hi, can you try patch 1.4.30 or newer? I introduced a new dialog popup when creating points from the Path and Point manager so that you get asked for the point type, Boundary or Text, and this subsequently stops the assert error.

Regards
   Jon

**Comment by rgleason** [comment]
Perhaps this should be closed?

**Comment by jongough** [comment]
Code is in OD 1.6

**Pull request closed without merging**
