### PR TITLE
Speedup when saving a file

### PR DESCRIPTION
**Pull request by did-g**
Hi,
Try to speedup  file saving.
Still too slow because it's redrawing too much opencpn viewport, saving a 20 000 points files take hours...

Regards
Didier

### CODE REVIEW

**Comment by jongough** [comment]
Hi, I have implemented this change in my own pull. I used 'unmanaged_map' for the check table as it is reported as being faster than 'map', but I have not done any timing tests.
I also have changed the update dialog box to only update once a second, if need be I could make this a selectable setting in the ini file so that the user could select the best update rate for what they are doing. Let me know.
Jon

**Comment by did-g** [comment]
Hi,
Great. but currently it doesn't build on my setup, dreaded 'isnan(double&) is ambiguous ' error in wx with gcc 4.8 and -std=c++11. It seems to work with gc 6.0 though  but for stupid reasons of mine I can't run it.

Do you know if c++11 is ok with xp? 

Regards
Didier

**Comment by jongough** [comment]
The only way I could get your or my version of this code to build was with c++11 enabled. I could not build with 'map' or unordered_map' without this. If I try an error is generated that __cplusplus is < 201103. 

I currently cannot do much checking on windows as I lost a hard disk that had all my virtual windows on it and I am slowly rebuilding that environment, but I now have to use VS2017 and newer software that is causing problems for others. I am also on a very slow internet connection with very limited downloads and Microsoft uses GBs for each 'runtime version' I try to use and I am running out of downloads trying to get it working. Sorry for that, but that is why Rick is doing some of the compiles for me.

Regards
   Jon

**Comment by did-g** [comment]
Hi

On Tue, Jan 9, 2018 at 9:14 PM, jongough <notifications@github.com> wrote:

> The only way I could get your or my version of this code to build was with
> c++11 enabled. I could not build with 'map' or unordered_map' without this.
> If I try an error is generated that __cplusplus is < 201103.
>
Interesting, on linux or window? As a matter of facts I used  the slower
map vs  unordered_map because it's already used elsewhere within opencpn
without using c++11, be able to use it would be great though, lot of nice
stuff in c11. On the other hand I'm wary of mixing compiler cplusplus
versions within the same executable.

—
> You are receiving this because you authored the thread.
>

log of windows built but visual 2015
https://ci.appveyor.com/project/did-g/ocpn-draw-pi/build/1.0.60

I currently cannot do much checking on windows as I lost a hard disk that
> had all my virtual windows on it and I am slowly rebuilding that
> environment, but I now have to use VS2017 and newer software that is
> causing problems for others. I am also on a very slow internet connection
> with very limited downloads and Microsoft uses GBs for each 'runtime
> version' I try to use and I am running out of downloads trying to get it
> working. Sorry for that, but that is why Rick is doing some of the compiles
> for me.
>
I can related to this, most of time I'm on a phone data plan. Once I tried
to build a compilation window box; after downloading 5 or 6 GB twice I had
nothing, err yes carrier put me on some low lane and every 15mn I was
disconnected and had to reset the phone.

  Regards
Didier

**Comment by jongough** [comment]
Hi Didier,
   Just put up patch 1.4.54 that allows compiling without c++11  and uses 'map' or if you select c++11 via option 'OD_CXX11' it will be compiled with 'unordered_map' and a guestimate of the size of the hash to help reduce the number of increases in size it needs. Can you give this a go and see if it helps.

   I just wish I could download a sensible sized iso for visual studio and install from that. But if you try the 'offline' install it wants to download over 20GB (if it works) and then is still likely to go to the internet to get 'patches' which again can be GB's!

Regards
   Jon

**Comment by did-g** [comment]
Hi,
Great job! Works well, test on linux with gcc 4.8 (broken c++11) , linux 6.0 in c++11 an windows.

Regards
Didier

**Pull request closed without merging**
