### PR TITLE
Priyankaprakasan patch 1

### PR DESCRIPTION
**Pull request by priyankaprakasan**
I have modified  GZ.cpp and ODUtils.cpp to draw rectangular GZ( need to draw four triangular GZs) instead of circular GZ around the boat.
Next I would like to update ( modify the first and second distance )the GZs that I have already drawn with respect to the velocity of the boat. For example, if the velocity is much
high GZs first and second distance would be longer, in order to reduce the impact of collision by other AIS objects.

My plan is to access the velocity of the boat from NMEA data file and modify the first and second distance of a particular GZ in ODNavobj.xml file.

Which cpp file deals with ODNavObj.xml file?

### CODE REVIEW

**Comment by jongough** [comment]
Have you tried OD 1.6.80 ? That has the option to build GZ'ds with arcs or straight lines. Why are you trying to do this again?

You also seem to be uploading 'new' files, but these files already exist. Unless you are really creating new files all your pull requests should be for updates to existing files. I can then check to see what you have done and understand if it is going to break or not the current code base. Then I can accept the pull request.

You need to ensure your repository is up to date with mine, then fork a new branch from my 'master' branch, give it a useful name, work on changes to that, then commit the changes, push to your repository, then issue a pull on mine.

To work on this now you really need to setup your own circleci, appveyor and cloudsmith accounts as all plugins will be delivered using the new Plugin Manager in OCPN. These accounts let you build automatically for all environments and test using these builds. It helps to ensure you have got everything you need in your repository. The OCPN developer manual should help you get setup with this stuff. It is new, so will be a little rough around the edges.

**Comment by priyankaprakasan** [comment]
Dear Jon,

I really do not want to replace your code. I uploaded the code since you
told me I have not shared my code.
I actually need how we can modify the first and second distance dynamically
outside Ocpn_draw?

I am thinking to do this with an another plugin which access the speed of
the boat from NMEA data.  That is why once I mentioned  about modification
on  ODNavobj.xml by another plugin.
For this purpose I gonna use Voyage Data Recorder plugin. My plan is to
access the velocity of the boat from NMEA file and modify ODNavobj.xml.

Kindly share your thoughts on this.
*Regards*

Priyanka

**Comment by jongough** [comment]
OD already gets all the information you need as it is registered with OCPN to get calls to "SetPositionFixEx" and that takes the information and updates teh "g_pfFix" structure. The information in this structure is what OCPN is using for all of its calculations. 

There is no API to allow dynamic changes and there is no API to allow the management of GZ'ds. Modifying the ODnavobj.xml will not do anything. This file is read when OD starts and is written when OD shutdown. All the information is kept in memory. The ODnavobj.xml.changes file is written to when objects are added, changed or deleted. It is only kept if the write to ODnavobj.xml is not competed at shutdown. It will then be read after ODnavobj.xml on restart and all of its items updated one at a time to end up with the same objects as when OD was last run.

You will have to change OD code to be able to do what you want. But you will have to do some serious thinking about zones that are not directly ahead of the boat, how do you control the minimum size and the maximum size, does the GZ grow or just mover further forward, what happens to the sizeds, how does the user control this change in size, how does the user switch from distance to time as a parameter, what happens when the boat stops, etc. All the changes have to be applied not only to the drawing of the GZ but to the selection capability (should happen automatically, but......).

This is not a trivial exercise to get right.

**Comment by jongough** [comment]
Closing as no apparent action occuring

**Pull request closed without merging**
